---
config: '.trivy.yaml'
misconfiguration:
  scanners:
    - 'terraform'
    - 'terraformplan-json'
    - 'terraformplan-snapshot'
  terraform:
    exclude-downloaded-modules: false
exit-code: 1
format: 'table'
report: 'all'
scan:
  disable-telemetry: true
severity:
  - 'UNKNOWN'
  - 'LOW'
  - 'MEDIUM'
  - 'HIGH'
  - 'CRITICAL'
table-mode:
  - 'summary'
  - 'detailed'
