---
on:
  push: {}
  workflow_dispatch:
    inputs:
      apply:
        description: 'Run `tofu apply`?'
        required: true
        default: false
        type: 'boolean'
      apply_wait:
        description: 'Wait x seconds before running `tofu apply`:'
        required: true
        default: 60
        type: 'number'
jobs:
  tofu:
    name: 'OpenTofu'
    runs-on: 'docker'
    steps:
      - name: 'Install necessary packages.'
        run: >-
          apk update --no-progress &&
          apk upgrade -la --no-progress --no-cache &&
          apk add --no-progress --no-cache \
            trivy opentofu-1.11 git nodejs-25
      - name: 'Checkout our git repository'
        uses: 'actions/checkout@v6'
      - name: 'Ensure our OpenTofu workspace is properly formatted.'
        run: |
          set -euo pipefail
          tofu fmt -check
      - name: 'Ensure our providers & backend are functional.'
        run: |
          set -euo pipefail
          tofu init -reconfigure
      - name: 'Ensure our workspace can read our environment.'
        run: |
          set -euo pipefail
          tofu plan -out="${{ env.FORGEJO_WORKSPACE }}/terraform.plan"
      - name: 'Scan our OpenTofu workspace for misconfigurations.'
        run: |
          set -euo pipefail
          trivy config -qc .trivy.yaml \
            "${{ env.FORGEJO_WORKSPACE }}/terraform.plan"
      - name: >-
          Apply our changes to our environment in
          ${{ inputs.apply_waits }} seconds.
        if: '${{ inputs.apply }}'
        run: |
          set -euo pipefail
          sleep "${{ inputs.apply_wait }}"
          tofu apply -auto-approve "${{ env.FORGEJO_WORKSPACE }}/terraform.plan"

    container:
      # image: 'docker.io/node:lts'
      # image: 'cgr.dev/chainguard/node:latest'
      image: 'cgr.dev/chainguard/wolfi-base:latest'
      env:
        TF_VAR_env: |-
          {
            "environment_name": "prod",
            "s3_endpoint": "https://s3.us-west-2.idrivee2.com/",
            "s3_bucket": "tfstate",
            "skip_validation": true,
            "pve_endpoint": "https://[fd67::200]:8006/"
          }
        TF_VAR_auth: |-
          {
            "users": [
              "root@pam",
              "root@pam"
            ],
            "passwords": [
              "${{ secrets.AUTH_PASS0 }}",
              "${{ secrets.AUTH_PASS1 }}"
            ]
          }
        AWS_REGION: 'us-west-2'
        AWS_ACCESS_KEY_ID: 'O1sh3RhWxWbn5bgOmflT'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
